name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_TITLE: "True"
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: "True"
          LANG_COUNT: 15
          SHOW_TOTAL: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LOC_CHART: "True"
